export default function getMaterias () {
    return [{
        Materiaid: "001",
        nome: 'Estrutura de Dados',
        codigo: 'COMP415',
        descricao : 'o ramo da computação que estuda os diversos mecanismos de organização de dados para atender aos diferentes requisitos de processamento. As estruturas de dados definem a organização, métodos de acesso e opções de processamento para a informação manipulada pelo programa',
        periodo: '2',
        nivelEsforco: 'Alto',
        professor: ['Rodrigo Faro', 'Jessie J', 'Zé Pilintra'],
        curso: ['Ciência da Computação', 'Engenharia de Computação'],
        matExpositivo : ['Material 1', "Material 2"],
        literatura : [' “Introduction to Algorithms”, de Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest e Clifford Stein', '“Algorithms Unlocked”, de Thomas H. Cormen', '“The Algorithm Design Manual”, de Steven S. Skiena'],
        questoes : ['Huxley [Prática]', 'HakerRank [Prática]', 'computersciencemaster [Teoria]'],
        areaRelevancia : ['Ótimização de Recursos','Inteligencia Artificial', 'Análise de complexidade de Algorítimos']
    },
    {
        Materiaid: "002",
        nome: 'Teoria dos Grafos',
        descricao :'A teoria dos grafos é um ramo da matemática que estuda as relações entre os objetos de um determinado conjunto. Para tal são empregadas estruturas chamadas de grafos, G(V,A), onde V é um conjunto não vazio de objetos denominados vértices e A é um conjunto de pares não ordenados de V, chamado arestas.',
        codigo: 'COMP420',
        periodo: '3',
        nivelEsforco: 'Médio',
        professor: ['Bob Marley', 'Anitta'],
        curso: ['Ciência da Computação', 'Engenharia de Computação'],
        matExpositivo : ['Ufrj Slides share Grafos', "Teoria dos Grafos slideplayer"],
        literatura : [' John A. Bondy, U.S. Rama Murty,  Graph Theory,  Springer, 2008.', 'Dieter Jungnickel, Graphs, Networks and Algorithms, Springer-Verlag, 2008.', 'N. Hartsfield, G. Ringel,  Pearls in Graph Theory: a comprehensive introduction, Dover, 2003.'],
        questoes : ['Huxley [Prática]', 'HakerRank [Prática]', 'Lista de Exercício UFMG [Teoria]', 'Lista de Exercício USP [Teoria]'],
        areaRelevancia : ['Ótimização de Recursos','Inteligencia Artificial', 'Desenvolvimento Web', 'Aplicações em Redes de Computadores']
    },
    {
        Materiaid: "003",
        nome: 'Matemática Discreta',
        codigo: 'COMP012',
        descricao :'Matemática discreta, também chamada matemática finita, é o estudo das estruturas algébricas que são fundamentalmente discretas, em vez de contínuas. Provê um conjunto de técnicas para modelar problemas em Ciência da Computação.',
        periodo: '1',
        nivelEsforco: 'Médio',
        professor: ['Lince Negra'],
        curso: ['Ciência da Computação', 'Engenharia de Computação'],
        matExpositivo : ['Ufrj Slides share Discreta', "Matemática Discreta slideplayer"],
        literatura : ['Matemática discreta: uma introdução, Ed Scheinerman', 'Matemática Discreta para Computação e informatica, Paulo Blauth'],
        questoes : ['ufpr Inf - Matemática discreta Exercícios', 'Matematica Discreta.pdf - EduCAPES'],
        areaRelevancia : ['Lógica para Computação','Teoria dos Grafos', 'Teoria dos Jogos', 'Criptografia', 'Programação Linear']
    },
    {
        Materiaid: "004",
        nome: 'Sistemas Operacionais',
        codigo: 'COMP225',
        descricao :'Fundamentalmente, um sistema operacional é um software, que pode ser o Linux, Windows, Android, macOS, UNIX, entre outros. No entanto, ele não resume aquilo que seus olhos conseguem ver ou ao que você consegue interagir. Em outras palavras, é um programa que conversa diretamente com o hardware da sua máquina.',
        periodo: '5',
        nivelEsforco: 'Baixo',
        professor: ['Sidney Magal'],
        curso: ['Ciência da Computação', 'Engenharia de Computação'],
        matExpositivo : ["UNIVESP Youtube Channel"],
        literatura : ['Sistemas Operacionais: Projetjos e Implementação, Adrew S. Tenenbaum, Albert S. Woodhull · 2009', 'Elucidando Os Sistemas Operacionais: Luciana Maura Aquaroni Geraldi · 2013'],
        questoes : ['Sistemas Operacionais em Questões, Alfredo Braga Furtado'],
        areaRelevancia : ['Mobile Programing','Hardware applications', 'Desenvolvimento', 'Programação paralela']
    },
    {
        Materiaid: "005",
        nome: 'Sistemas Digitais',
        codigo: 'ECOM478',
        descricao :'Um sistema digital é uma combinação de dispositivos projetados para manipular informação lógica ou quantidades físicas que são representadas no formato digital, ou seja, as quantidades só podem assumir valores discretos.',
        periodo: 'ELETIVA',
        nivelEsforco: 'Baixo',
        professor: ['Gugu Liberato'],
        curso: ['Engenharia de Computação'],
        matExpositivo : ["e-Aulas da USP Youtube Channel"],
        literatura : ['Sistemas Digitais: Fundamentos e Aplicações, Thomas Floyd · 2009', 'Sistemas Digitais, Frank Vahid · 2009'],
        questoes : ['Instituto Federal Catarinense - Lista de exercício 1 Sistemas Digitais'],
        areaRelevancia : ['Robótica', 'Circuitos digitais','Hardware applications', 'Eletrônica']
    },
    {
        Materiaid: "006",
        nome: 'Cálculo 2',
        codigo: 'COMP321',
        descricao:'No Cálculo Diferencial e Integral de Várias Variáveis, ou simplesmente, Cálculo II, são estudados o conceito de derivadas e integrais de funções reais de mais de uma variável, o que se aproxima um pouco mais dos problemas do mundo real.',
        periodo: 'ELETIVA',
        nivelEsforco: 'Alto',
        professor: ['Xi Ji Ping'],
        curso: ['Ciência da Computação', 'Engenharia de Computação'],
        matExpositivo : ["e-Aulas da USP Youtube Channel", "UNIVESP Youtube Channel"],
        literatura : ['Sistemas Digitais: Fundamentos e Aplicações, Thomas Floyd · 2009', 'Sistemas Digitais, Frank Vahid · 2009'],
        questoes : ['UFMG - 1° Sem. 2004 - Exame Especial',' Unicamp - 2° Sem. 2008 - P1 (com gabarito)', 'Unicamp - 2° Sem. 2016 - P1 - Turma Manhã (com gabarito)'],
        areaRelevancia : ['Inteligencia Artificial','Análise de Algorítimos', 'Hardware']
    },
    {
        Materiaid: "007",
        nome: 'Compiladores',
        codigo: 'COMP312',
        descricao:'Área de estudo que trabalhar o que é um compilador, brevemente um compilador é um programa que traduz o código escrito em uma linguagem de alto nível para código de máquina. Em resumo, traduz o código legível para os seres humanos e converte para a linguagem binária que o processador entende.',
        periodo: '5',
        nivelEsforco: 'Alto',
        professor: ['Susane von Richtofen'],
        curso: ['Ciência da Computação'],
        matExpositivo : [" Judson Santiago Youtube Channel"],
        literatura : ['Construindo Compiladores, Keith Daniel Cooper · 2013', 'Compiladores: Princípios E Práticas, Kenneth C. Louden · 2004'],
        questoes : ['Qconcursos - Compiladores',' Tamburetei - Exercícios de Compiladores'],
        areaRelevancia : ['Teoria da Computação','Programação', 'Hardware']
    },
    {
        Materiaid: "008",
        nome: 'Circuitos Digitais',
        codigo: 'ECOM001',
        descricao:'Os circuitos digitais ou circuitos lógicos são definidos como circuitos eletrônicos que empregam a utilização de sinais elétricos em apenas dois níveis de corrente para definir a representação de valores binários.', 
        periodo: '2',
        nivelEsforco: 'Baixo',
        professor: ['Carmem Miranda', 'Fred do Scooby Doo'],
        curso: ['Engenharia de Computação'],
        matExpositivo : ["e-Aulas da USP Youtube Channel"],
        literatura : ['Circuitos Digitais, Marisi Piagetti De Pádua · 2021', 'Circuitos Digitais: Série Apontamentos, Luiz Ricardo Mantovani Da Silva · 2019'],
        questoes : ['Circuitos Digitais – Terceira Lista de Exercícios, ifrn'],
        areaRelevancia : ['Eletronica','Sistemas Digitais', 'Hardware', 'Robótica']
    },
    {
        Materiaid: "009",
        nome: 'Física 2',
        codigo: 'ECOM678',
        descricao:'O segundo curso de Física básica possui um conteúdo bastante rico. Inicia-se com noções básicas de hidrostática e hidrodinâmica.',
        periodo: '3',
        nivelEsforco: 'Médio',
        professor: ['Melody', 'Celso Russomano', 'Rihanna', 'Bob Marley'],
        curso: ['Engenharia de Computação'],
        matExpositivo : ["e-Aulas da USP Youtube Channel"],
        literatura : ['Física 2: Física Térmica e Óptica Vol. 2', 'Física: Volume 2, Frederick J. Keller,W. Edward Gettys, Malcolm J. Skove · 1998 ·'],
        questoes : ['Física: Volume 2, Frederick J. Keller,W. Edward Gettys, Malcolm J. Skove · 1998', 'Lista de exercícios 2 - Física II IFRN'],
        areaRelevancia : ['Hardware', 'Robótica']
    },
    {
        Materiaid: "010",
        nome: 'Engenharia de Software',
        codigo: 'COMP021',
        descricao:'Engenharia de software é uma área da engenharia e da computação voltada à especificação, desenvolvimento, manutenção e criação de software, com a aplicação de tecnologias e práticas de gerência de projetos e outras disciplinas, visando organização, produtividade e qualidade.',
        periodo: '4',
        nivelEsforco: 'Baixo',
        professor: ['Chapolin Colorado', 'Chaves'],
        curso: ['Engenharia de Computação'],
        matExpositivo : ["e-Aulas Cruzeiro do Sul Virtua Youtube Channel", "UNIVESP Youtube Channel"],
        literatura : ['Engenharia de software: conceitos e práticas, Raul Sidnei Wazlawick · 2013', 'Introdução Ao Teste De Software, Marcio Delamaro, Mario Jino,José Maldonado · 2013'],
        questoes : ['1ª lista de exercícios — Givanaldo Rocha - Docentes - IFRN', 'PUC - Exercícios de Engenharia de Software'],
        areaRelevancia : ['Desenvolvimento Web', 'Desenvolvimento Mobile', 'Gerência de Projeto']
    },
    {
        Materiaid: "011",
        nome: 'Probabilidade e Estatística',
        descricao:'A teoria da Probabilidade é o estudo matemático na quantificação da aleatoriedade e incerteza de eventos na natureza; a Estatística é a ciência da coleta, descrição e análise de dados.',
        codigo: 'ECOM012',
        periodo: '4',
        nivelEsforco: 'Alto',
        professor: ['George Clooney'],
        curso: ['Engenharia de Computação'],
        matExpositivo : ["e-Aulas Cruzeiro do Sul Virtua Youtube Channel", "UNIVESP Youtube Channel"],
        literatura : ['Probabilidade e Variáveis Aleatórias, Marcos Nascimento Magalhães · 2006', 'Compreendendo Probabilidade e Estatística'],
        questoes : ['Compreendendo Probabilidade e Estatística - Livro Questões', 'UFMG - Coleção de Exercícios de Estatística e Probabilidade'],
        areaRelevancia : ['Ciência de Dados', 'Inteligência Artificial', 'Computação evolucionária']
    },
    {
        Materiaid: "012",
        nome: 'Eletrônica',
        codigo: 'ECOM035',
        descricao:'É o estudo das propriedades e aplicações de dispositivos que dependem do movimento de elétrons em semicondutores, gases ou no vácuo.',
        periodo: '6',
        nivelEsforco: 'Baixo',
        professor: ['Tutancamon', 'Bozo', 'Kurt Cobain'],
        curso: ['Engenharia de Computação'],
        matExpositivo : ["Brincando com Ideias Youtube Channel", "ABC da Eletrônica para iniciantes Youtube Channel"],
        literatura : ['Eletrônica Aplicada', 'Eletrônica digital, Alexandre Gaspary Haupt, Édison Pereira Dachi · 2016'],
        questoes : ['Eletrônica Digital [Livro]', 'Qconcursos - Eltrônica'],
        areaRelevancia : ['Hardware', 'Robótica', 'Sistemas digitais']
    },
    ]
}