export default function getMaterias() {
    return [{
            nome: 'Estrutura de Dados',
            codigo: 'COMP415',
            periodo: '2',
            nivelEsforco: 'Alto',
            professor: ['Rodrigo Faro', 'Jessie J', 'Zé Pilintra'],
            curso: ['Ciência da Computação', 'Engenharia de Computação'],
            matExpositivo: ['Material 1', "Material 2"],
            literatura:['Material 1', 'Material 2'],
            questoes: ['Questão 1', 'Questão 2'],
            areaRelevancia: ['Programação Competitiva','Engenharia de Software', 'Análise de Algoritmos']
        },
        {
            nome: 'Teoria dos Grafos',
            codigo: 'COMP420',
            periodo: '3',
            nivelEsforco: 'Médio',
            professor: ['Bob Marley', 'Anitta'],
            curso: ['Ciência da Computação', 'Engenharia de Computação'],
            matExpositivo: ['Material 1', "Material 2"],
            literatura:['Material 1', 'Material 2'],
            questoes: ['Questão 1', 'Questão 2'],
            areaRelevancia: ['Programação Distribuida','Inteligencia Artificial']
        },
        {
            nome: 'Matemática Discreta',
            codigo: 'COMP012',
            periodo: '1',
            nivelEsforco: 'Médio',
            professor: ['Lince Negra'],
            curso: ['Ciência da Computação', 'Engenharia de Computação'],
            matExpositivo: ['Material 1', "Material 2"],
            literatura:['Material 1', 'Material 2'],
            questoes: ['Questão 1', 'Questão 2'],
            areaRelevancia: ['Criptografia','Redes de Computadores', 'Análise de Algoritmos']
        },
        {
            nome: 'Sistemas Operacionais',
            codigo: 'COMP225',
            periodo: '5',
            nivelEsforco: 'Baixo',
            professor: ['Sidney Magal'],
            curso: ['Ciência da Computação', 'Engenharia de Computação'],
            matExpositivo: ['Material 1', "Material 2"],
            literatura:['Material 1', 'Material 2'],
            questoes: ['Questão 1', 'Questão 2'],
            areaRelevancia: ['Programação Distribuida','Redes de Computadores', 'Embarcados']
        },
        {
            nome: 'Sistemas Digitais',
            codigo: 'ECOM478',
            periodo: 'ELETIVA',
            nivelEsforco: 'Baixo',
            professor: ['Gugu Liberato'],
            curso: ['Engenharia de Computação'],
            matExpositivo: ['Material 1', "Material 2"],
            literatura:['Material 1', 'Material 2'],
            questoes: ['Questão 1', 'Questão 2'],
            areaRelevancia: ['Embarcados','Robótica', 'Sensores']
        },
        {
            nome: 'Cálculo 2',
            codigo: 'COMP321',
            periodo: 'ELETIVA',
            nivelEsforco: 'Alto',
            professor: ['Xi Ji Ping'],
            curso: ['Ciência da Computação', 'Engenharia de Computação'],
            matExpositivo: ['Material 1', "Material 2"],
            literatura:['Material 1', 'Material 2'],
            questoes: ['Questão 1', 'Questão 2'],
            areaRelevancia: ['-','Inteligencia Artificial', 'Análise de Algorítimos']
        },
        {
            nome: 'Compiladores',
            codigo: 'COMP312',
            periodo: '5',
            nivelEsforco: 'Alto',
            professor: ['Susane von Richtofen'],
            curso: ['Ciência da Computação'],
            matExpositivo: ['Material 1', "Material 2"],
            literatura:['Material 1', 'Material 2'],
            questoes: ['Questão 1', 'Questão 2'],
            areaRelevancia: ['Programação Distribuida','Inteligencia Artificial', 'Engenheria de Software']
        },
        {
            nome: 'Circuitos Digitais',
            codigo: 'ECOM001',
            periodo: '2',
            nivelEsforco: 'Baixo',
            professor: ['Carmem Miranda', 'Fred do Scooby Doo'],
            curso: ['Engenharia de Computação'],
            matExpositivo: ['Material 1', "Material 2"],
            literatura:['Material 1', 'Material 2'],
            questoes: ['Questão 1', 'Questão 2'],
            areaRelevancia: ['Robótica','Embarcados', 'Eletrônica']
        },
        {
            nome: 'Física 2',
            codigo: 'ECOM678',
            periodo: '3',
            nivelEsforco: 'Médio',
            professor: ['Melody', 'Celso Russomano', 'Rihanna', 'Bob Marley'],
            curso: ['Engenharia de Computação'],
            matExpositivo: ['Material 1', "Material 2"],
            literatura:['Material 1', 'Material 2'],
            questoes: ['Questão 1', 'Questão 2'],
            areaRelevancia: ['Robótica','Física Computacional', '-']
        },
        {
            nome: 'Engenharia de Software',
            codigo: 'COMP021',
            periodo: '4',
            nivelEsforco: 'Baixo',
            professor: ['Chapolin Colorado', 'Chaves'],
            curso: ['Engenharia de Computação'],
            matExpositivo: ['Material 1', "Material 2"],
            literatura:['Material 1', 'Material 2'],
            questoes: ['Questão 1', 'Questão 2'],
            areaRelevancia: ['Desenvolvimento Web','Programação alto nível', '-']
        },
        {
            nome: 'Probabilidade e Estatística',
            codigo: 'ECOM012',
            periodo: '4',
            nivelEsforco: 'Alto',
            professor: ['George Clooney'],
            curso: ['Engenharia de Computação'],
            matExpositivo: ['Material 1', "Material 2"],
            literatura:['Material 1', 'Material 2'],
            questoes: ['Questão 1', 'Questão 2'],
            areaRelevancia: ['Ciência de Dados','Inteligencia Artificial', 'Big Data']
        },
        {
            nome: 'Eletrônica',
            codigo: 'ECOM035',
            periodo: '6',
            nivelEsforco: 'Baixo',
            professor: ['Tutancamon', 'Bozo', 'Kurt Cobain'],
            curso: ['Engenharia de Computação'],
            matExpositivo: ['Material 1', "Material 2"],
            literatura:['Material 1', 'Material 2'],
            questoes: ['Questão 1', 'Questão 2'],
            areaRelevancia: ['Embarcados','Robótica', 'Programação baixo nível']
        },
    ]
}